Traceback (most recent call last):
  File "/home/users/wx83/GNN_baseline/GNN/train.py", line 295, in <module>
    axs[1].plot(epochs, train_acc_curve, label='Training Accuracy')
  File "/home/users/wx83/miniconda3/envs/gnn/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 1721, in plot
    lines = [*self._get_lines(self, *args, data=data, **kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/wx83/miniconda3/envs/gnn/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 303, in __call__
    yield from self._plot_args(
               ^^^^^^^^^^^^^^^^
  File "/home/users/wx83/miniconda3/envs/gnn/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 499, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (50,) and (0,)
